apiVersion: v1
kind: Secret
metadata:
  name: medimitra-agent-secret
data:
  google_api_key: QUl6YVN5QzVYNkZvXzcwRFZOb1h2eEliQ2RuamxFdDM2X3NVYVFVCg==
  mongouri: bW9uZ29kYitzcnY6Ly9tcmluYWxzYXR5YXJ0aGkyMDA1OmUyY1ZOZW5QY3ZDeDQwTzVAY2x1c3RlcjAuNWd5cGY1eS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjAK
  dbname: test
  bhuvan_access_token: ZThiNmEzMmZjMWVkNTU5NTA4YzNhNjNlZmZiM2YyMGM5NmU3NGIwZAo=
  langsmith_tracing: "true"
  langsmith_endpoint: https://api.smith.langchain.com
  langsmith_api_key: bHN2Ml9wdF81YmIyNTJmYjUxZDA0MzFiYjBkY2NiNzI1YmQ0MjgyNV85ODZmZmQ2ZTQyCg==
  langsmith_project: cHItd29ydGh3aGlsZS1ldmlkZW5jZS03NAo=
type: Opaque