apiVersion: v1
kind: Secret
metadata:
  name: medimitra-backend-secret
data:
  mongouri: bW9uZ29kYitzcnY6Ly9tcmluYWxzYXR5YXJ0aGkyMDA1OmUyY1ZOZW5QY3ZDeDQwTzVAY2x1c3RlcjAuNWd5cGY1eS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjAK
  secret_key: bWVkaW1pdHJhQG1ocGFnNDUwMQo=
  google_clientid: 291291284445-hdgpjdu2rosif7gvp82hrrsucpaqcn78.apps.googleusercontent.com
  google_client_secret: R09DU1BYLTFHekw4QXpnUjFlZldzd3hPek1NUmQ0TF9JWFcK
  salt: "10"
  email: medimitra32@gmail.com
  email_password: cGNvcXhlaHpyeGhoaWJyYgo=
  callbackurl: http://localhost:5001/auth/google/callback
  profilelink: http://localhost:5173/profile
  redirect_dashboard: http://localhost:5173/dashboard
type: Opaque