apiVersion: v1
kind: Secret
metadata:
  name: medimitra-backend-secret
data:
  mongouri: bW9uZ29kYitzcnY6Ly9tcmluYWxzYXR5YXJ0aGkyMDA1OmUyY1ZOZW5QY3ZDeDQwTzVAY2x1c3RlcjAuNWd5cGY1eS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjAK
  secret_key: bWVkaW1pdHJhQG1ocGFnNDUwMQo=
  google_clientid: 291291284445-hdgpjdu2rosif7gvp82hrrsucpaqcn78.apps.googleusercontent.com
  google_client_secret: R09DU1BYLTFHekw4QXpnUjFlZldzd3hPek1NUmQ0TF9JWFcK
  salt: MTAK
  email: bWVkaW1pdHJhMzJAZ21haWwuY29tCg==
  email_password: cGNvcXhlaHpyeGhoaWJyYgo=
  callbackurl: aHR0cDovL2xvY2FsaG9zdDo1MDAxL2F1dGgvZ29vZ2xlL2NhbGxiYWNrCg==
  profilelink: aHR0cDovL2xvY2FsaG9zdDo1MTczL3Byb2ZpbGUK
  redirect_dashboard: aHR0cDovL2xvY2FsaG9zdDo1MTczL2Rhc2hib2FyZAo=
type: Opaque