name: Medimitra CI/CD Pipeline Agent
on: workflow_dispatch
env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: us-east-2
  ECR_AGENT_REGISTRY: ${{ secrets.ECR_AGENT_REGISTRY }}
  ECR_AGENT_REPO: medimitra-agent
  EKS_CLUSTER: medimitra-eks-cluster
jobs:
  BUILD_AND_PUBLISH:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./agent
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5.0.0

      - name: build and push docker image
        uses: docker://ghcr.io/kciter/aws-ecr-action:latest
        with:
          access_key: ${{ env.AWS_ACCESS_KEY }}
          secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ env.ECR_AGENT_REGISTRY }}
          repo: ${{ env.ECR_AGENT_REPO }}
          region: ${{ env.AWS_REGION }}
          tags: latest,${{ github.run_number }}
          daemon_off: false
          dockerfile: agent/Dockerfile
          context: agent

  DeployToEKS:
    needs: BUILD_AND_PUBLISH
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5.0.0

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: update kube config
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}

      - name: Login to ecr
        run: kubectl create secret docker-registry regcred --docker-server=${{ env.ECR_AGENT_REGISTRY }} --docker-username=AWS --docker-password=$(aws ecr get-login-password)"

      - name: Deploy Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.12
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          cluster-name: ${{ env.EKS_CLUSTER }}
          chart-path: helm/medimitra-charts
          namespace: default
          values: agentimage=${{ env.ECR_AGENT_REGISTRY }}/${{ env.ECR_AGENT_REPO }},agenttag=latest
          name: medimitra-agent
